#!/bin/env sh

SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR/../.."

export XDG_RUNTIME_DIR="/run/user/$(id -u)"

WLR_BACKENDS=drm,libinput \
WLR_DRM_DEVICES=/dev/dri/card0 \
WLR_RENDER_DRM_DEVICE=/dev/dri/renderD129 \
WLR_RENDERER=vulkan \
LAVA_FRAME_PROBE=1 \
	stdbuf -oL -eL ./build/compositor/compositor \
		>"$HOME/lava-compositor.log" 2>&1

