// Generated by npidl compiler
// DO NOT EDIT - all changes will be lost

import NPRPC

public struct FontNotFound: NPRPCError {
  public var path: String = ""

  public init() {}

  public init(path: String)   {
    self.path = path
  }

  public var message: String { "FontNotFound" }
}


// MARK: - Marshal FontNotFound
public func marshal_FontNotFound(buffer: FlatBuffer, offset: Int, data: FontNotFound) {
  buffer.storeBytes(of: UInt32(0), toByteOffset: offset + 0, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 4, string: data.path)
}

// MARK: - Unmarshal FontNotFound
public func unmarshal_FontNotFound(buffer: UnsafeRawPointer, offset: Int) -> FontNotFound {
  var result = FontNotFound()
  result.path = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 4)
  return result
}

public struct ArenaNotFound: NPRPCError {
  public var arenaId: String = ""

  public init() {}

  public init(arenaId: String)   {
    self.arenaId = arenaId
  }

  public var message: String { "ArenaNotFound" }
}


// MARK: - Marshal ArenaNotFound
public func marshal_ArenaNotFound(buffer: FlatBuffer, offset: Int, data: ArenaNotFound) {
  buffer.storeBytes(of: UInt32(1), toByteOffset: offset + 0, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 4, string: data.arenaId)
}

// MARK: - Unmarshal ArenaNotFound
public func unmarshal_ArenaNotFound(buffer: UnsafeRawPointer, offset: Int) -> ArenaNotFound {
  var result = ArenaNotFound()
  result.arenaId = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 4)
  return result
}

fileprivate struct lava_M1: Codable, Sendable {
  public var _1: String = ""
  public var _2: Float = 0.0

  public init() {}

  public init(_1: String, _2: Float)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal lava_M1
fileprivate func marshal_lava_M1(buffer: FlatBuffer, offset: Int, data: lava_M1) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
  buffer.storeBytes(of: data._2, toByteOffset: offset + 8, as: Float.self)
}

// MARK: - Unmarshal lava_M1
fileprivate func unmarshal_lava_M1(buffer: UnsafeRawPointer, offset: Int) -> lava_M1 {
  var result = lava_M1()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: Float.self)
  return result
}

fileprivate struct lava_M2: Codable, Sendable {
  public var _1: UInt32 = 0

  public init() {}

  public init(_1: UInt32)   {
    self._1 = _1
  }
}


// MARK: - Marshal lava_M2
fileprivate func marshal_lava_M2(buffer: FlatBuffer, offset: Int, data: lava_M2) {
  buffer.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt32.self)
}

// MARK: - Unmarshal lava_M2
fileprivate func unmarshal_lava_M2(buffer: UnsafeRawPointer, offset: Int) -> lava_M2 {
  var result = lava_M2()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  return result
}

fileprivate struct lava_M3: Codable, Sendable {
  public var _1: String = ""

  public init() {}

  public init(_1: String)   {
    self._1 = _1
  }
}


// MARK: - Marshal lava_M3
fileprivate func marshal_lava_M3(buffer: FlatBuffer, offset: Int, data: lava_M3) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
}

// MARK: - Unmarshal lava_M3
fileprivate func unmarshal_lava_M3(buffer: UnsafeRawPointer, offset: Int) -> lava_M3 {
  var result = lava_M3()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  return result
}

public protocol CompositorProtocol {
  func registerFont(path: String, pixelSize: Float) throws -> UInt32
  func attachArena(arenaId: String) throws
  func present()
}

// Client proxy for Compositor
// Pure Swift implementation with direct marshalling
final public class Compositor: NPRPCObject, @unchecked Sendable {
  public override class var classId: String {
    "lava/lava.Compositor"
  }

  public required init(handle: UnsafeMutableRawPointer)   {
    super.init(handle: handle)
  }

  public required init(from decoder: Decoder) throws   {
    try super.init(from: decoder)
  }

  public func registerFont(path: String, pixelSize: Float) async throws -> UInt32   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(172)
    buffer.commit(44)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(0), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M1()
    inArgs._1 = path
    inArgs._2 = pixelSize
    marshal_lava_M1(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M2(buffer: responseData, offset: 16)
    return out._1
  }

  public func attachArena(arenaId: String) async throws   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(168)
    buffer.commit(40)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(1), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M3()
    inArgs._1 = arenaId
    marshal_lava_M3(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != 0 { throw UnexpectedReplyError(message: "Unexpected reply") }
  }

  public func present() async   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(32)
    buffer.commit(32)
    guard let data = buffer.data else { return  }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(2), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    guard let finalData = buffer.data else { return  }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send unreliable (no reply expected)
    do {
      try await sendAsync(buffer: buffer, timeout: timeout)
    } catch {
      // Fire-and-forget: ignore communication errors
    }
  }

}

// Servant base for Compositor
open class CompositorServant: NPRPCServant, CompositorProtocol, @unchecked Sendable {
  public override init() { super.init() }

  public override func getClass() -> String   {
    return "lava/lava.Compositor"
  }

  open func registerFont(path: String, pixelSize: Float) throws -> UInt32   {
    fatalError("Subclass must implement registerFont")
  }

  open func attachArena(arenaId: String) throws   {
    fatalError("Subclass must implement attachArena")
  }

  open func present()   {
    fatalError("Subclass must implement present")
  }

  // Dispatch incoming RPC calls
  public override func dispatch(buffer: FlatBuffer, remoteEndpoint: NPRPCEndpoint)   {
    guard let data = buffer.data else { return }

    // Read function index from CallHeader
    let functionIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.CallHeader>.offset(of: \NPRPC.impl.CallHeader.function_idx)!), as: UInt8.self)

    switch functionIdx     {
      case 0: // RegisterFont
        // Validate input buffer for untrusted interface
        guard check_1S2Ff32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M1(buffer: data, offset: 32)
        
        do {
          let __ret_val = try registerFont(path: ia._1, pixelSize: ia._2)
          // Prepare output buffer
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(20)
          obuf.commit(20)
          // Marshal output arguments
          var out_data = lava_M2()
          out_data._1 = __ret_val

          marshal_lava_M2(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as FontNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          guard let exData = obuf.data else { return }
          marshal_FontNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 1: // AttachArena
        // Validate input buffer for untrusted interface
        guard check_1S(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M3(buffer: data, offset: 32)
        
        do {
          try attachArena(arenaId: ia._1)
          // Send success
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Success)
        }
        catch let e as ArenaNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          guard let exData = obuf.data else { return }
          marshal_ArenaNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 2: // Present
        
        present()
        // Send success
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Success)
      default:
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_UnknownFunctionIdx)
    } // switch
  } // dispatch
}


// Safety check for lava_M1
fileprivate func check_1S2Ff32(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 12) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 0) else { return false }
  return true
}


// Safety check for lava_M3
fileprivate func check_1S(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 8) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 0) else { return false }
  return true
}


// MARK: - Exception Handling
fileprivate func lava_throwException(buffer: FlatBuffer) -> any Error {
  guard let data = buffer.constData else {
    return RuntimeError(message: "Failed to read exception data")
  }
  let exId = data.load(fromByteOffset: 16, as: UInt32.self)
  switch exId {
  case 0:
    return unmarshal_FontNotFound(buffer: data, offset: 16)
  case 1:
    return unmarshal_ArenaNotFound(buffer: data, offset: 16)
  default:
    return RuntimeError(message: "Unknown exception id: \(exId)")
  }
}
