// Generated by npidl compiler
// DO NOT EDIT - all changes will be lost

import NPRPC

public struct FontNotFound: NPRPCError {
  public var path: String = ""

  public init() {}

  public init(path: String)   {
    self.path = path
  }

  public var message: String { "FontNotFound" }
}


// MARK: - Marshal FontNotFound
public func marshal_FontNotFound(buffer: FlatBuffer, offset: Int, data: FontNotFound) {
  buffer.storeBytes(of: UInt32(0), toByteOffset: offset + 0, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 4, string: data.path)
}

// MARK: - Unmarshal FontNotFound
public func unmarshal_FontNotFound(buffer: UnsafeRawPointer, offset: Int) -> FontNotFound {
  var result = FontNotFound()
  result.path = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 4)
  return result
}

public struct ImageNotFound: NPRPCError {
  public var path: String = ""

  public init() {}

  public init(path: String)   {
    self.path = path
  }

  public var message: String { "ImageNotFound" }
}


// MARK: - Marshal ImageNotFound
public func marshal_ImageNotFound(buffer: FlatBuffer, offset: Int, data: ImageNotFound) {
  buffer.storeBytes(of: UInt32(1), toByteOffset: offset + 0, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 4, string: data.path)
}

// MARK: - Unmarshal ImageNotFound
public func unmarshal_ImageNotFound(buffer: UnsafeRawPointer, offset: Int) -> ImageNotFound {
  var result = ImageNotFound()
  result.path = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 4)
  return result
}

public struct ImageInfo: Codable, Sendable {
  public var id: UInt32 = 0
  public var width: UInt32 = 0
  public var height: UInt32 = 0

  public init() {}

  public init(id: UInt32, width: UInt32, height: UInt32)   {
    self.id = id
    self.width = width
    self.height = height
  }
}


// MARK: - Marshal ImageInfo
public func marshal_ImageInfo(buffer: FlatBuffer, offset: Int, data: ImageInfo) {
  buffer.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt32.self)
  buffer.storeBytes(of: data.width, toByteOffset: offset + 4, as: UInt32.self)
  buffer.storeBytes(of: data.height, toByteOffset: offset + 8, as: UInt32.self)
}

// MARK: - Unmarshal ImageInfo
public func unmarshal_ImageInfo(buffer: UnsafeRawPointer, offset: Int) -> ImageInfo {
  var result = ImageInfo()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  result.width = buffer.load(fromByteOffset: offset + 4, as: UInt32.self)
  result.height = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  return result
}

public struct ArenaNotFound: NPRPCError {
  public var arenaId: String = ""

  public init() {}

  public init(arenaId: String)   {
    self.arenaId = arenaId
  }

  public var message: String { "ArenaNotFound" }
}


// MARK: - Marshal ArenaNotFound
public func marshal_ArenaNotFound(buffer: FlatBuffer, offset: Int, data: ArenaNotFound) {
  buffer.storeBytes(of: UInt32(2), toByteOffset: offset + 0, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 4, string: data.arenaId)
}

// MARK: - Unmarshal ArenaNotFound
public func unmarshal_ArenaNotFound(buffer: UnsafeRawPointer, offset: Int) -> ArenaNotFound {
  var result = ArenaNotFound()
  result.arenaId = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 4)
  return result
}

public struct SurfaceNotFound: NPRPCError {
  public var surfaceId: UInt32 = 0

  public init() {}

  public init(surfaceId: UInt32)   {
    self.surfaceId = surfaceId
  }

  public var message: String { "SurfaceNotFound" }
}


// MARK: - Marshal SurfaceNotFound
public func marshal_SurfaceNotFound(buffer: FlatBuffer, offset: Int, data: SurfaceNotFound) {
  buffer.storeBytes(of: UInt32(3), toByteOffset: offset + 0, as: UInt32.self)
  buffer.storeBytes(of: data.surfaceId, toByteOffset: offset + 4, as: UInt32.self)
}

// MARK: - Unmarshal SurfaceNotFound
public func unmarshal_SurfaceNotFound(buffer: UnsafeRawPointer, offset: Int) -> SurfaceNotFound {
  var result = SurfaceNotFound()
  result.surfaceId = buffer.load(fromByteOffset: offset + 4, as: UInt32.self)
  return result
}

public struct InputEvent: Codable, Sendable {
  public var serial: UInt32 = 0
  public var kind: UInt32 = 0
  public var x: Float = 0.0
  public var y: Float = 0.0
  public var button: Int32 = 0
  public var mods: Int32 = 0

  public init() {}

  public init(serial: UInt32, kind: UInt32, x: Float, y: Float, button: Int32, mods: Int32)   {
    self.serial = serial
    self.kind = kind
    self.x = x
    self.y = y
    self.button = button
    self.mods = mods
  }
}


// MARK: - Marshal InputEvent
public func marshal_InputEvent(buffer: FlatBuffer, offset: Int, data: InputEvent) {
  buffer.storeBytes(of: data.serial, toByteOffset: offset + 0, as: UInt32.self)
  buffer.storeBytes(of: data.kind, toByteOffset: offset + 4, as: UInt32.self)
  buffer.storeBytes(of: data.x, toByteOffset: offset + 8, as: Float.self)
  buffer.storeBytes(of: data.y, toByteOffset: offset + 12, as: Float.self)
  buffer.storeBytes(of: data.button, toByteOffset: offset + 16, as: Int32.self)
  buffer.storeBytes(of: data.mods, toByteOffset: offset + 20, as: Int32.self)
}

// MARK: - Unmarshal InputEvent
public func unmarshal_InputEvent(buffer: UnsafeRawPointer, offset: Int) -> InputEvent {
  var result = InputEvent()
  result.serial = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  result.kind = buffer.load(fromByteOffset: offset + 4, as: UInt32.self)
  result.x = buffer.load(fromByteOffset: offset + 8, as: Float.self)
  result.y = buffer.load(fromByteOffset: offset + 12, as: Float.self)
  result.button = buffer.load(fromByteOffset: offset + 16, as: Int32.self)
  result.mods = buffer.load(fromByteOffset: offset + 20, as: Int32.self)
  return result
}

public struct InputAck: Codable, Sendable {
  public var serial: UInt32 = 0

  public init() {}

  public init(serial: UInt32)   {
    self.serial = serial
  }
}


// MARK: - Marshal InputAck
public func marshal_InputAck(buffer: FlatBuffer, offset: Int, data: InputAck) {
  buffer.storeBytes(of: data.serial, toByteOffset: offset + 0, as: UInt32.self)
}

// MARK: - Unmarshal InputAck
public func unmarshal_InputAck(buffer: UnsafeRawPointer, offset: Int) -> InputAck {
  var result = InputAck()
  result.serial = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  return result
}

fileprivate struct lava_M1: Codable, Sendable {
  public var _1: String = ""
  public var _2: Float = 0.0

  public init() {}

  public init(_1: String, _2: Float)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal lava_M1
fileprivate func marshal_lava_M1(buffer: FlatBuffer, offset: Int, data: lava_M1) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
  buffer.storeBytes(of: data._2, toByteOffset: offset + 8, as: Float.self)
}

// MARK: - Unmarshal lava_M1
fileprivate func unmarshal_lava_M1(buffer: UnsafeRawPointer, offset: Int) -> lava_M1 {
  var result = lava_M1()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: Float.self)
  return result
}

fileprivate struct lava_M2: Codable, Sendable {
  public var _1: UInt32 = 0

  public init() {}

  public init(_1: UInt32)   {
    self._1 = _1
  }
}


// MARK: - Marshal lava_M2
fileprivate func marshal_lava_M2(buffer: FlatBuffer, offset: Int, data: lava_M2) {
  buffer.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt32.self)
}

// MARK: - Unmarshal lava_M2
fileprivate func unmarshal_lava_M2(buffer: UnsafeRawPointer, offset: Int) -> lava_M2 {
  var result = lava_M2()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  return result
}

fileprivate struct lava_M3: Codable, Sendable {
  public var _1: String = ""
  public var _2: UInt32 = 0

  public init() {}

  public init(_1: String, _2: UInt32)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal lava_M3
fileprivate func marshal_lava_M3(buffer: FlatBuffer, offset: Int, data: lava_M3) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
  buffer.storeBytes(of: data._2, toByteOffset: offset + 8, as: UInt32.self)
}

// MARK: - Unmarshal lava_M3
fileprivate func unmarshal_lava_M3(buffer: UnsafeRawPointer, offset: Int) -> lava_M3 {
  var result = lava_M3()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  return result
}

fileprivate struct lava_M4: Codable, Sendable {
  public var _1: ImageInfo = ImageInfo()

  public init() {}

  public init(_1: ImageInfo)   {
    self._1 = _1
  }
}


// MARK: - Marshal lava_M4
fileprivate func marshal_lava_M4(buffer: FlatBuffer, offset: Int, data: lava_M4) {
  marshal_ImageInfo(buffer: buffer, offset: offset + 0, data: data._1)
}

// MARK: - Unmarshal lava_M4
fileprivate func unmarshal_lava_M4(buffer: UnsafeRawPointer, offset: Int) -> lava_M4 {
  var result = lava_M4()
  result._1 = unmarshal_ImageInfo(buffer: buffer, offset: offset + 0)
  return result
}

fileprivate struct lava_M5: Codable, Sendable {
  public var _1: [UInt8] = []
  public var _2: UInt32 = 0

  public init() {}

  public init(_1: [UInt8], _2: UInt32)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal lava_M5
fileprivate func marshal_lava_M5(buffer: FlatBuffer, offset: Int, data: lava_M5) {
  NPRPC.marshal_fundamental_vector(buffer: buffer, offset: offset + 0, vector: data._1)
  buffer.storeBytes(of: data._2, toByteOffset: offset + 8, as: UInt32.self)
}

// MARK: - Unmarshal lava_M5
fileprivate func unmarshal_lava_M5(buffer: UnsafeRawPointer, offset: Int) -> lava_M5 {
  var result = lava_M5()
  result._1 = NPRPC.unmarshal_fundamental_vector(buffer: buffer, offset: offset + 0)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  return result
}

fileprivate struct lava_M6: Codable, Sendable {
  public var _1: String = ""
  public var _2: UInt32 = 0
  public var _3: UInt32 = 0
  public var _4: String = ""

  public init() {}

  public init(_1: String, _2: UInt32, _3: UInt32, _4: String)   {
    self._1 = _1
    self._2 = _2
    self._3 = _3
    self._4 = _4
  }
}


// MARK: - Marshal lava_M6
fileprivate func marshal_lava_M6(buffer: FlatBuffer, offset: Int, data: lava_M6) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
  buffer.storeBytes(of: data._2, toByteOffset: offset + 8, as: UInt32.self)
  buffer.storeBytes(of: data._3, toByteOffset: offset + 12, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data._4)
}

// MARK: - Unmarshal lava_M6
fileprivate func unmarshal_lava_M6(buffer: UnsafeRawPointer, offset: Int) -> lava_M6 {
  var result = lava_M6()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  result._3 = buffer.load(fromByteOffset: offset + 12, as: UInt32.self)
  result._4 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  return result
}

fileprivate struct lava_M7: Codable, Sendable {
  public var _1: [String] = []

  public init() {}

  public init(_1: [String])   {
    self._1 = _1
  }
}


// MARK: - Marshal lava_M7
fileprivate func marshal_lava_M7(buffer: FlatBuffer, offset: Int, data: lava_M7) {
  NPRPC.marshal_string_vector(buffer: buffer, offset: offset + 0, vector: data._1)
}

// MARK: - Unmarshal lava_M7
fileprivate func unmarshal_lava_M7(buffer: UnsafeRawPointer, offset: Int) -> lava_M7 {
  var result = lava_M7()
  result._1 = NPRPC.unmarshal_string_vector(buffer: buffer, offset: offset + 0)
  return result
}

fileprivate struct lava_M8: Codable, Sendable {
  public var _1: String = ""

  public init() {}

  public init(_1: String)   {
    self._1 = _1
  }
}


// MARK: - Marshal lava_M8
fileprivate func marshal_lava_M8(buffer: FlatBuffer, offset: Int, data: lava_M8) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
}

// MARK: - Unmarshal lava_M8
fileprivate func unmarshal_lava_M8(buffer: UnsafeRawPointer, offset: Int) -> lava_M8 {
  var result = lava_M8()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  return result
}

fileprivate struct lava_M9: Codable, Sendable {
  public var _1: UInt32 = 0
  public var _2: String = ""

  public init() {}

  public init(_1: UInt32, _2: String)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal lava_M9
fileprivate func marshal_lava_M9(buffer: FlatBuffer, offset: Int, data: lava_M9) {
  buffer.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt32.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 4, string: data._2)
}

// MARK: - Unmarshal lava_M9
fileprivate func unmarshal_lava_M9(buffer: UnsafeRawPointer, offset: Int) -> lava_M9 {
  var result = lava_M9()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  result._2 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 4)
  return result
}

public protocol CompositorProtocol {
  func registerFont(path: String, pixelSize: Float) throws -> UInt32
  func registerImage(path: String, maxPixelSize: UInt32) throws -> ImageInfo
  func registerImageData(bytes: [UInt8], maxPixelSize: UInt32) throws -> ImageInfo
  func releaseImage(id: UInt32)
  func createSurface(arenaId: String, width: UInt32, height: UInt32, title: String) throws -> UInt32
  func destroySurface(surfaceId: UInt32) throws
  func present(surfaceId: UInt32)
  func subscribeInput(surfaceId: UInt32, stream: NPRPCBidiStream<InputEvent, InputAck>) async throws
  func takeDroppedPaths(surfaceId: UInt32) throws -> [String]
  func getClipboard(surfaceId: UInt32) throws -> String
  func setClipboard(surfaceId: UInt32, text: String) throws
}

// Client proxy for Compositor
// Pure Swift implementation with direct marshalling
final public class Compositor: NPRPCObject, @unchecked Sendable {
  public override class var classId: String {
    "lava/lava.Compositor"
  }

  public required init(handle: UnsafeMutableRawPointer)   {
    super.init(handle: handle)
  }

  public required init(from decoder: Decoder) throws   {
    try super.init(from: decoder)
  }

  public func registerFont(path: String, pixelSize: Float) async throws -> UInt32   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(172)
    buffer.commit(44)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(0), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M1()
    inArgs._1 = path
    inArgs._2 = pixelSize
    marshal_lava_M1(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M2(buffer: responseData, offset: 16)
    return out._1
  }

  public func registerImage(path: String, maxPixelSize: UInt32) async throws -> ImageInfo   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(172)
    buffer.commit(44)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(1), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M3()
    inArgs._1 = path
    inArgs._2 = maxPixelSize
    marshal_lava_M3(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M4(buffer: responseData, offset: 16)
    return out._1
  }

  public func registerImageData(bytes: [UInt8], maxPixelSize: UInt32) async throws -> ImageInfo   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(172)
    buffer.commit(44)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(2), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M5()
    inArgs._1 = bytes
    inArgs._2 = maxPixelSize
    marshal_lava_M5(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M4(buffer: responseData, offset: 16)
    return out._1
  }

  public func releaseImage(id: UInt32) async throws   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(36)
    buffer.commit(36)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(3), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M2()
    inArgs._1 = id
    marshal_lava_M2(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply != 0 { throw UnexpectedReplyError(message: "Unexpected reply") }
  }

  public func createSurface(arenaId: String, width: UInt32, height: UInt32, title: String) async throws -> UInt32   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(184)
    buffer.commit(56)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(4), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M6()
    inArgs._1 = arenaId
    inArgs._2 = width
    inArgs._3 = height
    inArgs._4 = title
    marshal_lava_M6(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M2(buffer: responseData, offset: 16)
    return out._1
  }

  public func destroySurface(surfaceId: UInt32) async throws   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(36)
    buffer.commit(36)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(5), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M2()
    inArgs._1 = surfaceId
    marshal_lava_M2(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != 0 { throw UnexpectedReplyError(message: "Unexpected reply") }
  }

  public func present(surfaceId: UInt32) async   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(36)
    buffer.commit(36)
    guard let bufData = buffer.data else { return  }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(6), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M2()
    inArgs._1 = surfaceId
    marshal_lava_M2(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { return  }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send unreliable (no reply expected)
    do {
      try await sendAsync(buffer: buffer, timeout: timeout)
    } catch {
      // Fire-and-forget: ignore communication errors
    }
  }

  public func subscribeInput(surfaceId: UInt32) throws -> NPRPCBidiStream<InputAck, InputEvent>   {
    let streamId = nprpc_generate_stream_id()

    // Prepare StreamInit buffer
    let buffer = FlatBuffer()
    buffer.prepare(52)
    buffer.commit(52)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write StreamInit message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: impl.MessageId.StreamInitialization.rawValue, toByteOffset: 4, as: UInt32.self)
    data.storeBytes(of: impl.MessageType.Request.rawValue, toByteOffset: 8, as: UInt32.self)
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self)  // reserved

    // Write StreamInit fields
    data.storeBytes(of: streamId, toByteOffset: 16, as: UInt64.self)  // offset 0
    data.storeBytes(of: poaIdx, toByteOffset: 24, as: UInt16.self)  // offset 8
    data.storeBytes(of: UInt8(0), toByteOffset: 26, as: UInt8.self)  // interface_idx at offset 10
    data.storeBytes(of: objectId, toByteOffset: 32, as: UInt64.self)  // offset 16 (after 5-byte pad)
    data.storeBytes(of: UInt8(7), toByteOffset: 40, as: UInt8.self)  // func_idx at offset 24
    data.storeBytes(of: impl.StreamKind.Bidi.rawValue, toByteOffset: 41, as: UInt8.self)
    data.storeBytes(of: defaultReaderWindow, toByteOffset: 44, as: UInt32.self)  // initial_credits at offset 28

    // Marshal input arguments
    var inArgs = lava_M2()
    inArgs._1 = surfaceId
    marshal_lava_M2(buffer: buffer, offset: 48, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    guard let session = nprpc_object_get_session(self.handle),
          let streamManager = nprpc_session_get_stream_manager(session) else {
      throw RuntimeError(message: "Failed to get session for stream")
    }

    let stream = NPRPC.createStreamManagerBidiStream(streamManager: streamManager, streamId: streamId, buffer: buffer, initialPayloadCapacity: 132, unreliable: false, producerWindow: defaultReaderWindow, serializer: { (buffer: FlatBuffer, offset: Int, value: InputAck) in NPRPC.marshal_stream_struct(buffer: buffer, offset: offset, rootSize: 4, value: value) { buf, off, elem in marshal_InputAck(buffer: buf, offset: off, data: elem) } }, deserializer: { (data: UnsafeRawPointer, _: Int) in unmarshal_InputEvent(buffer: data, offset: 0) })
    let result = nprpc_session_stream_send_init(session, buffer.handle, self.timeout)
    if result == 1 { throw lava_throwException(buffer: buffer) }
    if result != 0 { throw RuntimeError(message: "StreamInit failed (code: \(result))") }
    return stream
  }

  public func takeDroppedPaths(surfaceId: UInt32) async throws -> [String]   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(36)
    buffer.commit(36)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(8), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M2()
    inArgs._1 = surfaceId
    marshal_lava_M2(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M7(buffer: responseData, offset: 16)
    return out._1
  }

  public func getClipboard(surfaceId: UInt32) async throws -> String   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(36)
    buffer.commit(36)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(9), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M2()
    inArgs._1 = surfaceId
    marshal_lava_M2(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = responseBuffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_lava_M8(buffer: responseData, offset: 16)
    return out._1
  }

  public func setClipboard(surfaceId: UInt32, text: String) async throws   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(172)
    buffer.commit(44)
    guard let bufData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    bufData.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    bufData.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    bufData.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    bufData.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    bufData.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    bufData.storeBytes(of: UInt8(10), toByteOffset: 19, as: UInt8.self)  // function_idx
    bufData.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = lava_M9()
    inArgs._1 = surfaceId
    inArgs._2 = text
    marshal_lava_M9(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try Task.checkCancellation()
    let responseBuffer = try await sendAsyncReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: responseBuffer)
    if stdReply == 1 { throw lava_throwException(buffer: responseBuffer) }
    if stdReply != 0 { throw UnexpectedReplyError(message: "Unexpected reply") }
  }

}

// Servant base for Compositor
open class CompositorServant: NPRPCServant, CompositorProtocol, @unchecked Sendable {
  public override init() { super.init() }

  public override func getClass() -> String   {
    return "lava/lava.Compositor"
  }

  open func registerFont(path: String, pixelSize: Float) throws -> UInt32   {
    fatalError("Subclass must implement registerFont")
  }

  open func registerImage(path: String, maxPixelSize: UInt32) throws -> ImageInfo   {
    fatalError("Subclass must implement registerImage")
  }

  open func registerImageData(bytes: [UInt8], maxPixelSize: UInt32) throws -> ImageInfo   {
    fatalError("Subclass must implement registerImageData")
  }

  open func releaseImage(id: UInt32)   {
    fatalError("Subclass must implement releaseImage")
  }

  open func createSurface(arenaId: String, width: UInt32, height: UInt32, title: String) throws -> UInt32   {
    fatalError("Subclass must implement createSurface")
  }

  open func destroySurface(surfaceId: UInt32) throws   {
    fatalError("Subclass must implement destroySurface")
  }

  open func present(surfaceId: UInt32)   {
    fatalError("Subclass must implement present")
  }

  open func subscribeInput(surfaceId: UInt32, stream: NPRPCBidiStream<InputEvent, InputAck>) async throws   {
    fatalError("Subclass must implement subscribeInput")
  }

  open func takeDroppedPaths(surfaceId: UInt32) throws -> [String]   {
    fatalError("Subclass must implement takeDroppedPaths")
  }

  open func getClipboard(surfaceId: UInt32) throws -> String   {
    fatalError("Subclass must implement getClipboard")
  }

  open func setClipboard(surfaceId: UInt32, text: String) throws   {
    fatalError("Subclass must implement setClipboard")
  }

  // Dispatch incoming RPC calls
  public override func dispatch(buffer: FlatBuffer, remoteEndpoint: NPRPCEndpoint)   {
    guard let data = buffer.data else { return }

    // Check message type to route streaming vs regular calls
    let msgId = data.load(fromByteOffset: MemoryLayout<NPRPC.impl.Header>.offset(of: \NPRPC.impl.Header.msg_id)!, as: UInt32.self)

    if msgId == impl.MessageId.StreamInitialization.rawValue     {
      let streamFuncIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.StreamInit>.offset(of: \NPRPC.impl.StreamInit.func_idx)!), as: UInt8.self)
      switch streamFuncIdx       {
        case 7: // SubscribeInput
          // Streaming method dispatch
          guard let data = buffer.data else { return }
          let streamId = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.StreamInit>.offset(of: \NPRPC.impl.StreamInit.stream_id)!), as: UInt64.self)

          // Validate input buffer for untrusted interface
          guard check_1Fu32(buffer: data, bufferSize: buffer.size, offset: 48) else           {
            makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
            return
          }

          // Unmarshal input arguments
          let ia = unmarshal_lava_M2(buffer: data, offset: 48)

          guard let sessionCtx = self.sessionContext,
                let streamManager = nprpc_get_stream_manager(sessionCtx) else {
            makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
            return
          }
          let initialCredits = data.load(fromByteOffset: 44, as: UInt32.self)
          let stream = NPRPC.createStreamManagerBidiStream(streamManager: streamManager, streamId: streamId, buffer: buffer, initialPayloadCapacity: 152, unreliable: false, initialCredits: initialCredits, serializer: { (buffer: FlatBuffer, offset: Int, value: InputEvent) in NPRPC.marshal_stream_struct(buffer: buffer, offset: offset, rootSize: 24, value: value) { buf, off, elem in marshal_InputEvent(buffer: buf, offset: off, data: elem) } }, deserializer: { (data: UnsafeRawPointer, _: Int) in unmarshal_InputAck(buffer: data, offset: 0) })
          nprpc_stream_manager_defer_stream_start(streamManager, streamId)
          switch nprpcProbeStreamInit(
            body: { [self] in
              try await self.subscribeInput(surfaceId: ia._1, stream: stream)
            },
            installFirstAccess: { stream.reader.onFirstAccess = $0 }
          ) {
          case .started:
            makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Success)
          case .initError(let error):
            do {
              throw error
            } catch let e as SurfaceNotFound {
              let obuf = buffer
              obuf.consume(obuf.size)
              obuf.prepare(24)
              obuf.commit(24)
              guard let exData = obuf.data else { return }
              marshal_SurfaceNotFound(buffer: obuf, offset: 16, data: e)
              exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
              exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
              exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
            } catch {
              makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
            }
          }
        default:
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_UnknownFunctionIdx)
      } // switch streamFuncIdx
      return
    }

    // Read function index from CallHeader
    let functionIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.CallHeader>.offset(of: \NPRPC.impl.CallHeader.function_idx)!), as: UInt8.self)

    switch functionIdx     {
      case 0: // RegisterFont
        // Validate input buffer for untrusted interface
        guard check_1S2Ff32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M1(buffer: data, offset: 32)
        
        do {
          let __ret_val = try registerFont(path: ia._1, pixelSize: ia._2)
          // Prepare output buffer
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(20)
          obuf.commit(20)
          // Marshal output arguments
          var out_data = lava_M2()
          out_data._1 = __ret_val

          marshal_lava_M2(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as FontNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          guard let exData = obuf.data else { return }
          marshal_FontNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 1: // RegisterImage
        // Validate input buffer for untrusted interface
        guard check_1S2Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M3(buffer: data, offset: 32)
        
        do {
          let __ret_val = try registerImage(path: ia._1, maxPixelSize: ia._2)
          // Prepare output buffer
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          // Marshal output arguments
          var out_data = lava_M4()
          out_data._1 = __ret_val

          marshal_lava_M4(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as ImageNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          guard let exData = obuf.data else { return }
          marshal_ImageNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 2: // RegisterImageData
        // Validate input buffer for untrusted interface
        guard check_1VFu82Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M5(buffer: data, offset: 32)
        
        do {
          let __ret_val = try registerImageData(bytes: ia._1, maxPixelSize: ia._2)
          // Prepare output buffer
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          // Marshal output arguments
          var out_data = lava_M4()
          out_data._1 = __ret_val

          marshal_lava_M4(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as ImageNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          guard let exData = obuf.data else { return }
          marshal_ImageNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 3: // ReleaseImage
        // Validate input buffer for untrusted interface
        guard check_1Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M2(buffer: data, offset: 32)
        
        releaseImage(id: ia._1)
        // Send success
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Success)
      case 4: // CreateSurface
        // Validate input buffer for untrusted interface
        guard check_1S2Fu323Fu324S(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M6(buffer: data, offset: 32)
        
        do {
          let __ret_val = try createSurface(arenaId: ia._1, width: ia._2, height: ia._3, title: ia._4)
          // Prepare output buffer
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(20)
          obuf.commit(20)
          // Marshal output arguments
          var out_data = lava_M2()
          out_data._1 = __ret_val

          marshal_lava_M2(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as ArenaNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(28)
          obuf.commit(28)
          guard let exData = obuf.data else { return }
          marshal_ArenaNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 5: // DestroySurface
        // Validate input buffer for untrusted interface
        guard check_1Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M2(buffer: data, offset: 32)
        
        do {
          try destroySurface(surfaceId: ia._1)
          // Send success
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Success)
        }
        catch let e as SurfaceNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(24)
          obuf.commit(24)
          guard let exData = obuf.data else { return }
          marshal_SurfaceNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 6: // Present
        // Validate input buffer for untrusted interface
        guard check_1Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M2(buffer: data, offset: 32)
        
        present(surfaceId: ia._1)
      case 8: // TakeDroppedPaths
        // Validate input buffer for untrusted interface
        guard check_1Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M2(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(152)
        obuf.commit(24)
        
        do {
          let __ret_val = try takeDroppedPaths(surfaceId: ia._1)
          // Marshal output arguments
          var out_data = lava_M7()
          out_data._1 = __ret_val

          marshal_lava_M7(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as SurfaceNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(24)
          obuf.commit(24)
          guard let exData = obuf.data else { return }
          marshal_SurfaceNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 9: // GetClipboard
        // Validate input buffer for untrusted interface
        guard check_1Fu32(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M2(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(152)
        obuf.commit(24)
        
        do {
          let __ret_val = try getClipboard(surfaceId: ia._1)
          // Marshal output arguments
          var out_data = lava_M8()
          out_data._1 = __ret_val

          marshal_lava_M8(buffer: buffer, offset: 16, data: out_data)
          guard let outData = buffer.data else { return }
          outData.storeBytes(of: UInt32(buffer.size), toByteOffset: 0, as: UInt32.self)
          outData.storeBytes(of: impl.MessageId.BlockResponse.rawValue, toByteOffset: 4, as: UInt32.self)
          outData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch let e as SurfaceNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(24)
          obuf.commit(24)
          guard let exData = obuf.data else { return }
          marshal_SurfaceNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      case 10: // SetClipboard
        // Validate input buffer for untrusted interface
        guard check_1Fu322S(buffer: data, bufferSize: buffer.size, offset: 32) else         {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_BadInput)
          return
        }

        // Unmarshal input arguments
        let ia = unmarshal_lava_M9(buffer: data, offset: 32)
        
        do {
          try setClipboard(surfaceId: ia._1, text: ia._2)
          // Send success
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Success)
        }
        catch let e as SurfaceNotFound {
          let obuf = buffer
          obuf.consume(obuf.size)
          obuf.prepare(24)
          obuf.commit(24)
          guard let exData = obuf.data else { return }
          marshal_SurfaceNotFound(buffer: obuf, offset: 16, data: e)
          exData.storeBytes(of: UInt32(obuf.size), toByteOffset: 0, as: UInt32.self)
          exData.storeBytes(of: impl.MessageId.Exception.rawValue, toByteOffset: 4, as: UInt32.self)
          exData.storeBytes(of: impl.MessageType.Answer.rawValue, toByteOffset: 8, as: UInt32.self)
        }
        catch {
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_Unknown)
        }
      default:
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.Error_UnknownFunctionIdx)
    } // switch
  } // dispatch
}


// Safety check for lava_M1
fileprivate func check_1S2Ff32(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 12) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 0) else { return false }
  return true
}


// Safety check for lava_M3
fileprivate func check_1S2Fu32(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 12) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 0) else { return false }
  return true
}


// Safety check for lava_M5
fileprivate func check_1VFu82Fu32(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 12) else { return false }
  guard NPRPC.check_vector_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 0, elementSize: 1) else { return false }
  return true
}


// Safety check for lava_M2
fileprivate func check_1Fu32(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 4) else { return false }
  return true
}


// Safety check for lava_M6
fileprivate func check_1S2Fu323Fu324S(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 24) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 0) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 16) else { return false }
  return true
}


// Safety check for lava_M9
fileprivate func check_1Fu322S(buffer: UnsafeRawPointer, bufferSize: Int, offset: Int) -> Bool {
  guard NPRPC.check_struct_bounds(bufferSize: bufferSize, offset: offset, structSize: 12) else { return false }
  guard NPRPC.check_string_bounds(buffer: buffer, bufferSize: bufferSize, offset: offset + 4) else { return false }
  return true
}


// MARK: - Exception Handling
fileprivate func lava_throwException(buffer: FlatBuffer) -> any Error {
  guard let data = buffer.constData else {
    return RuntimeError(message: "Failed to read exception data")
  }
  let exId = data.load(fromByteOffset: 16, as: UInt32.self)
  switch exId {
  case 0:
    return unmarshal_FontNotFound(buffer: data, offset: 16)
  case 1:
    return unmarshal_ImageNotFound(buffer: data, offset: 16)
  case 2:
    return unmarshal_ArenaNotFound(buffer: data, offset: 16)
  case 3:
    return unmarshal_SurfaceNotFound(buffer: data, offset: 16)
  default:
    return RuntimeError(message: "Unknown exception id: \(exId)")
  }
}
