#!/usr/bin/env bash
# Count lines of code, leaving out generated stubs, vendored code and build output.
# Usage: scripts/cloc.sh [extra cloc args, e.g. --by-file]
set -euo pipefail

cd "$(dirname "$0")/.."

command -v cloc >/dev/null || { echo "cloc not found (install the 'cloc' package)" >&2; exit 1; }

# Generated by scripts/gen_stubs.sh from idl/lava.npidl.
generated='^(\./)?(Sources/LavaIDL|compositor/src/gen)(/|$)'
# Vendored or cloned third-party trees, and anything a build produces.
vendored='^(\./)?(third-party|canvas/third-party)(/|$)'
build='(^|/)(\.build|build|build-release|builddir)(/|$)'

exec cloc \
  --fullpath \
  --not-match-d="($generated|$vendored|$build)" \
  --exclude-dir=.git,.swiftpm,.vm,.cache \
  "$@" \
  .
